version: '3'

vars:
  PROJECT_NAME: toolshare
  NEXT_PORT: 3000
  SUPABASE_PORT: 54321
  SUPABASE_STUDIO_PORT: 54323
  SUPABASE_DB_PORT: 54322

includes:
  setup: ./tasks/Taskfile.setup.yml
  dev: ./tasks/Taskfile.dev.yml
  database: ./tasks/Taskfile.database.yml

tasks:
  # ============================================================================
  # MAIN ORCHESTRATION TASKS (Entry points only)
  # ============================================================================
  
  setup:
    desc: Complete project setup - installs dependencies, sets up environment, and initializes Supabase
    deps: [setup:install-deps, setup:setup-env, setup:fix-docker-auth, setup:setup-supabase]

  dev:
    desc: Start development server with Supabase (full stack)
    deps: [database:supabase-start, dev:dev-only]

  db-reset:
    desc: Reset database, generate types, and seed all data (including users)
    deps: [database:db-reset]

  validate:
    desc: Run format, lint, build and fail if any are bad
    deps: [dev:format-fix, dev:lint-fix, dev:format-check, dev:lint, dev:build]

  # ============================================================================
  # QUICK ACCESS TASKS
  # ============================================================================

  status:
    desc: Show project status and help information
    cmds:
      - |
        echo "🔧 {{.PROJECT_NAME}} - Quick Status"
        echo "=================================="
        echo ""
        echo "📊 SERVICES:"
        echo "  Next.js: http://localhost:{{.NEXT_PORT}}"
        echo "  Supabase Studio: http://localhost:{{.SUPABASE_STUDIO_PORT}}"
        echo "  Supabase API: http://localhost:{{.SUPABASE_PORT}}"


