version: '3'

tasks:
  # ============================================================================
  # CLEANUP TASKS
  # ============================================================================

  clean:
    silent: true
    desc: Clean build artifacts and temporary files
    cmds:
      - |
        rm -rf .next
        rm -rf node_modules/.cache
        rm -rf .turbo

  clean-all:
    silent: true
    desc: Clean everything including node_modules (requires reinstall)
    cmds:
      - |
        rm -rf .next
        rm -rf node_modules
        rm -rf .turbo
        echo "⚠️  Run 'task install-deps' to reinstall dependencies"

  # ============================================================================
  # MONITORING & DEBUGGING
  # ============================================================================

  monitor:
    silent: true
    desc: Monitor all services and show status
    cmds:
      - |
        echo "📊 Service Monitoring"
        echo "===================="
        echo ""
        echo "🔍 Checking Next.js..."
        if curl -s http://localhost:3000 > /dev/null; then
          echo "✅ Next.js running"
        else
          echo "❌ Next.js not running"
        fi
        echo ""
        echo "🔍 Checking Supabase API..."
        if curl -s http://localhost:54321/rest/v1/ > /dev/null; then
          echo "✅ Supabase API running"
        else
          echo "❌ Supabase API not running"
        fi
        echo ""
        echo "🔍 Checking Supabase Studio..."
        if curl -s http://localhost:54323 > /dev/null; then
          echo "✅ Supabase Studio running"
        else
          echo "❌ Supabase Studio not running"
        fi

  debug-env:
    silent: true
    desc: Debug environment variables (without exposing secrets)
    cmds:
      - |
        echo "🔍 Environment Debug Info"
        echo "========================="
        echo "NODE_ENV: $NODE_ENV"
        echo "NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-not set}"
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:-not set}"
        echo "NOVU_API_KEY: ${NOVU_API_KEY:-not set}"
        echo "NEXT_PUBLIC_NOVU_APP_ID: ${NEXT_PUBLIC_NOVU_APP_ID:-not set}"

  docker-fix-auth:
    silent: true
    desc: Fix Docker authentication issues (standalone task)
    cmds:
      - |
        docker logout public.ecr.aws || true
        echo "💡 If issues persist, try: docker login public.ecr.aws"

  clear-task-cache:
    silent: true
    desc: Clear Task runner cache
    cmds:
      - |
        rm -rf .task
        echo "💡 Run 'task dev' again to start development" 